import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const { isSignedIn } = useUser();

  const { data: posts } = api.post.list.useQuery();

  return (
    <>
      <Head>
        <title>Tick</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!isSignedIn && <SignInButton />}
        {isSignedIn && <SignOutButton />}
        {posts?.map((post) => <div key={post.id}>{post.content}</div>)}
        {posts?.length === 0 && 'No posts yet'}
      </main>
    </>
  );
}
